name: gg337
channels:
  - defaults
dependencies:
  - python=3.10
  - re
  - pandas
  - csv
  - tqdm
  - vaderSentiment
  - spacy
  - nltk
  - ftfy
  - unidecode
  - pip  # Include pip for installing langdetect
  - pip:
      - langdetect  # Install langdetect via pip
